const SITE_URL="https://radar-de-concursos-mpc.netlify.app/";
const concursos=[
 {orgao:"São Sebastião PREV",titulo:"Concurso Público — Edital 01/2026",local:"São Sebastião — SP",vagas:"Consulte o edital",nivel:"medio superior",salario:"Consulte o edital",prazo:"08 out",banca:"Instituto Mais",status:"aberto",destaque:true,link:"https://www.institutomais.org.br/"},
 {orgao:"FUNDACI",titulo:"Concurso Público — Edital 01/2026",local:"São Paulo — SP",vagas:"Consulte o edital",nivel:"medio superior",salario:"Consulte o edital",prazo:"24 set",banca:"Instituto Mais",status:"aberto",destaque:true,link:"https://www.institutomais.org.br/"},
 {orgao:"Prefeitura de Carmo da Mata",titulo:"Concurso Público 01/2026",local:"Carmo da Mata — MG",vagas:"Consulte o edital",nivel:"medio superior",salario:"Consulte o edital",prazo:"02 out",banca:"FADEPRP",status:"aberto",destaque:false,link:"https://www.carmodamata.mg.gov.br/"},
 {orgao:"Prefeitura de Tanguá",titulo:"Concurso Público 01/2026",local:"Tanguá — RJ",vagas:"23 vagas + CR",nivel:"medio superior",salario:"Consulte o edital",prazo:"Consulte o edital",banca:"Fonte oficial",status:"edital",destaque:true,link:"https://tangua.rj.gov.br/"}
];
let statusAtual="aberto";const $=s=>document.querySelector(s);const cards=$("#cards"),captura=$("#captura"),erro=$("#erro");
function textoStatus(s){return({aberto:"Inscrições abertas",edital:"Edital publicado",banca:"Banca definida",autorizado:"Concursos autorizados",previsto:"Concursos previstos",provas:"Provas anteriores"})[s]}
function render(){const q=$("#busca").value.trim().toLowerCase(),n=$("#nivel").value;const lista=concursos.filter(c=>c.status===statusAtual&&(`${c.orgao} ${c.titulo} ${c.local} ${c.banca}`.toLowerCase().includes(q))&&(n==="todos"||c.nivel.includes(n)));$("#status-label").textContent=textoStatus(statusAtual).toUpperCase();$("#contador").textContent=`${lista.length} resultado${lista.length===1?"":"s"}`;cards.innerHTML=lista.map((c,i)=>`<article class="card">${c.destaque?'<span class="badge">DESTAQUE</span>':""}<span class="tag">${c.orgao}</span><h3>${c.titulo}</h3><div class="meta"><span>📍 ${c.local}</span><span>👥 ${c.vagas}</span><span>🎓 ${c.nivel.includes("medio")&&c.nivel.includes("superior")?"Vários níveis":c.nivel}</span><span>💰 ${c.salario}</span></div><div class="card-bottom"><div><div class="deadline">Prazo: ${c.prazo}</div><small>Fonte/Banca: ${c.banca}</small></div><button class="details" data-index="${concursos.indexOf(c)}">Ver fonte oficial</button></div></article>`).join("");$("#empty").hidden=lista.length>0;document.querySelectorAll(".details").forEach(b=>b.onclick=()=>abrirDetalhe(Number(b.dataset.index)))}
function abrirDetalhe(i){if(localStorage.getItem("radarMpcLiberado")==="true")return window.open(concursos[i].link,"_blank","noopener");captura.hidden=false}
function mostrarCodigo(){captura.hidden=false;$("#etapa-dados").hidden=true;$("#etapa-codigo").hidden=false;setTimeout(()=>$("#codigo").focus(),50)}
async function pedirCodigo(){erro.hidden=true;const nome=$("#nome").value.trim(),whatsapp=$("#whatsapp").value.replace(/\D/g,""),objetivo=$("#objetivo").value;if(nome.length<2||whatsapp.length<10){erro.textContent="Informe seu nome e um WhatsApp válido com DDD.";erro.hidden=false;return}const btn=$("#pedir-codigo");btn.disabled=true;btn.textContent="AGUARDE...";try{const body=new URLSearchParams({"form-name":"radar-leads",nome,whatsapp,objetivo,origem:"radar-de-concursos-mpc"});const response=await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:body.toString()});if(!response.ok)throw new Error();localStorage.setItem("radarMpcCodigoPendente","true");mostrarCodigo();const msg=encodeURIComponent(`Olá, Prof. Lucas! Meu nome é ${nome}. Quero o código para acessar o Radar de Concursos MPC. Meu objetivo: ${objetivo}.\n\nDepois de receber o código, volto ao site por este link:\n${SITE_URL}`);window.open(`https://hotm.io/falarcomproflucasmpc?text=${msg}`,"_blank","noopener")}catch{erro.textContent="Não foi possível registrar agora. Tente novamente.";erro.hidden=false}finally{btn.disabled=false;btn.textContent="PEDIR CÓDIGO NO WHATSAPP"}}
async function validar(){erro.hidden=true;const codigo=$("#codigo").value.trim().toUpperCase();if(codigo.length!==6)return;try{const r=await fetch("/api/validar-codigo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({codigo})});if(!r.ok)throw new Error();localStorage.setItem("radarMpcLiberado","true");localStorage.removeItem("radarMpcCodigoPendente");captura.hidden=true}catch{erro.textContent="Código inválido. Confira e tente novamente.";erro.hidden=false}}
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelector(".tab.active").classList.remove("active");t.classList.add("active");statusAtual=t.dataset.status;render()});$("#busca").oninput=render;$("#nivel").onchange=render;$("#buscar").onclick=()=>document.querySelector("#oportunidades").scrollIntoView();$("#fechar").onclick=()=>captura.hidden=true;$("#pedir-codigo").onclick=pedirCodigo;$("#liberar").onclick=validar;$("#codigo").oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"");if(localStorage.getItem("radarMpcLiberado")!=="true"){if(localStorage.getItem("radarMpcCodigoPendente")==="true")mostrarCodigo();else setTimeout(()=>captura.hidden=false,60000)}render();
